### ISSUE TITLE
No Show?

### ISSUE THREAD

**Issue by AvelythDraike** [Andr3w246/KazdraReloaded#9]
I subscribed to the Kazdra Reloaded Race mod for Stormbound (Steam) However when I start a new game the Kazdra do not appear in the selectable races

**Comment by Andr3w246** [comment]
Make sure you have a race extender installed. I recommend Xbawx's character extender. Here's a link: https://steamcommunity.com/sharedfiles/filedetails/?id=729426722

**Comment by Andr3w246** [comment]
Going to assume this was solved because no response. Closing.
